/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#20201f",
        "secondary-fixed-dim": "#c7c6c6",
        "tertiary-container": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "secondary": "#c7c6c6",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary": "#ffffff",
        "inverse-primary": "#5d5f5f",
        "surface": "#131313",
        "on-secondary-container": "#b5b5b5",
        "primary-fixed-dim": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353535",
        "secondary-fixed": "#e3e2e2",
        "primary-container": "#e2e2e2",
        "on-tertiary-container": "#636565",
        "secondary-container": "#464747",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#2f3131",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#c6c6c7",
        "on-primary-fixed-variant": "#454747",
        "tertiary-fixed": "#e2e2e2",
        "on-background": "#e5e2e1",
        "on-primary-container": "#636565",
        "surface-bright": "#393939",
        "on-secondary": "#303031",
        "on-secondary-fixed-variant": "#464747",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#454747",
        "inverse-surface": "#e5e2e1",
        "outline": "#8e9192",
        "on-primary-fixed": "#1a1c1c",
        "on-surface-variant": "#c4c7c8",
        "primary": "#ffffff",
        "background": "#131313",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary": "#2f3131",
        "surface-variant": "#353535",
        "outline-variant": "#444748"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "unit": "4px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "label-sm": ["Sora"],
        "headline-lg": ["Sora"],
        "label-md": ["Sora"],
        "headline-xl": ["Sora"],
        "body-md": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "body-lg": ["Sora"],
        "code-md": ["Sora"],
        "display-massive": ["Sora"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "code-md": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-massive": ["clamp(3rem, 8vw, 10rem)", { "lineHeight": "0.9", "letterSpacing": "-0.04em", "fontWeight": "800" }]
      }
    },
  },
  plugins: [],
}
