// ============================================================================
// JSX / TSX Validation & Repair Engine
// ============================================================================
//
// Validates generated Remotion component code for structural correctness
// before it reaches the Babel compiler. Catches and repairs common LLM
// generation errors like unbalanced braces, extra parentheses, missing
// commas in style objects, and malformed JSX.
// ============================================================================

import { transform } from "sucrase";

export interface ValidationReport {
  isValid: boolean;
  errors: ValidationError[];
  repairedCode: string | null;
  repairApplied: boolean;
}

export interface ValidationError {
  type:
    | "unbalanced_braces"
    | "unbalanced_parens"
    | "unbalanced_jsx"
    | "missing_comma"
    | "extra_closing"
    | "syntax_error"
    | "structural_error";
  message: string;
  line?: number;
  column?: number;
}

// ── Bracket Balance Checker ─────────────────────────────────────────────────

interface BalanceResult {
  balanced: boolean;
  braceCount: number;   // { }
  parenCount: number;   // ( )
  bracketCount: number; // [ ]
  errors: ValidationError[];
}

/**
 * Checks whether all brackets, braces, and parentheses are balanced.
 * Ignores characters inside strings, template literals, and comments.
 */
function checkBracketBalance(code: string): BalanceResult {
  let braceCount = 0;
  let parenCount = 0;
  let bracketCount = 0;
  const errors: ValidationError[] = [];

  let inSingleQuote = false;
  let inDoubleQuote = false;
  let inTemplateLiteral = false;
  let inLineComment = false;
  let inBlockComment = false;
  let lineNumber = 1;

  for (let i = 0; i < code.length; i++) {
    const ch = code[i];
    const next = i + 1 < code.length ? code[i + 1] : "";
    const prev = i > 0 ? code[i - 1] : "";

    // Track line numbers
    if (ch === "\n") {
      lineNumber++;
      if (inLineComment) inLineComment = false;
      continue;
    }

    // Skip block comments
    if (inBlockComment) {
      if (ch === "*" && next === "/") {
        inBlockComment = false;
        i++;
      }
      continue;
    }

    // Skip line comments
    if (inLineComment) continue;

    // Detect comment starts
    if (!inSingleQuote && !inDoubleQuote && !inTemplateLiteral) {
      if (ch === "/" && next === "/") {
        inLineComment = true;
        continue;
      }
      if (ch === "/" && next === "*") {
        inBlockComment = true;
        i++;
        continue;
      }
    }

    // Handle string boundaries
    if (!inDoubleQuote && !inTemplateLiteral && ch === "'" && prev !== "\\") {
      inSingleQuote = !inSingleQuote;
      continue;
    }
    if (!inSingleQuote && !inTemplateLiteral && ch === '"' && prev !== "\\") {
      inDoubleQuote = !inDoubleQuote;
      continue;
    }
    if (!inSingleQuote && !inDoubleQuote && ch === "`" && prev !== "\\") {
      inTemplateLiteral = !inTemplateLiteral;
      continue;
    }

    // Skip string content
    if (inSingleQuote || inDoubleQuote || inTemplateLiteral) continue;

    // Count brackets
    if (ch === "{") braceCount++;
    if (ch === "}") {
      braceCount--;
      if (braceCount < 0) {
        errors.push({
          type: "extra_closing",
          message: `Extra closing brace '}' at line ${lineNumber}`,
          line: lineNumber,
        });
      }
    }
    if (ch === "(") parenCount++;
    if (ch === ")") {
      parenCount--;
      if (parenCount < 0) {
        errors.push({
          type: "extra_closing",
          message: `Extra closing parenthesis ')' at line ${lineNumber}`,
          line: lineNumber,
        });
      }
    }
    if (ch === "[") bracketCount++;
    if (ch === "]") {
      bracketCount--;
      if (bracketCount < 0) {
        errors.push({
          type: "extra_closing",
          message: `Extra closing bracket ']' at line ${lineNumber}`,
          line: lineNumber,
        });
      }
    }
  }

  if (braceCount !== 0) {
    errors.push({
      type: "unbalanced_braces",
      message: `Unbalanced braces: ${braceCount > 0 ? braceCount + " unclosed" : Math.abs(braceCount) + " extra closing"}`,
    });
  }
  if (parenCount !== 0) {
    errors.push({
      type: "unbalanced_parens",
      message: `Unbalanced parentheses: ${parenCount > 0 ? parenCount + " unclosed" : Math.abs(parenCount) + " extra closing"}`,
    });
  }

  return {
    balanced: braceCount === 0 && parenCount === 0 && bracketCount === 0 && errors.length === 0,
    braceCount,
    parenCount,
    bracketCount,
    errors,
  };
}

// ── Structural Pattern Detector ─────────────────────────────────────────────

/**
 * Detects common malformed JSX patterns generated by LLMs.
 */
function detectStructuralIssues(code: string): ValidationError[] {
  const errors: ValidationError[] = [];
  const lines = code.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trimEnd();
    const lineNum = i + 1;

    // Detect triple closing )))  }  patterns — common LLM error
    if (/\)\)\)\}/.test(line)) {
      errors.push({
        type: "structural_error",
        message: `Suspicious triple-close pattern ')))}' at line ${lineNum}`,
        line: lineNum,
      });
    }

    // Detect '})}' without matching opener nearby
    if (/\}\)\}/.test(line) && !/\.map\(|\.filter\(|\.reduce\(|\.forEach\(|\.flatMap\(/.test(lines.slice(Math.max(0, i - 15), i).join("\n"))) {
      // Only flag if there's no .map() within 15 lines before
      errors.push({
        type: "structural_error",
        message: `Suspicious close pattern '})}' without matching map/filter at line ${lineNum}`,
        line: lineNum,
      });
    }
  }

  return errors;
}

// ── Auto-Repair Engine ──────────────────────────────────────────────────────

/**
 * Attempts to automatically repair common syntax issues in generated TSX.
 * Returns the repaired code or null if repair was not possible.
 */
export function repairGeneratedCode(code: string): { code: string; repairs: string[] } {
  let repaired = code;
  const repairs: string[] = [];

  // ── Repair 0: Remove stray backslashes from JSX tags ───────────────────
  const originalCodeForBackslash = repaired;
  repaired = repaired.replace(/<\s*([\\/]+)\s*([a-zA-Z_$][a-zA-Z0-9_$-]*)/g, (match, slashes, tagName) => {
    if (slashes.includes('\\')) {
      return '</' + tagName;
    }
    return match;
  });
  repaired = repaired.replace(/([\\/]+)\s*>/g, (match, slashes) => {
    if (slashes.includes('\\')) {
      return ' />';
    }
    return match;
  });
  if (repaired !== originalCodeForBackslash) {
    repairs.push("Removed stray backslashes from JSX tags");
  }

  // ── Repair 1: Fix missing commas in object literals (style objects) ────
  // Pattern: property value on one line, then a new property key on the next
  // e.g.:
  //   opacity: 1
  //   transform: '...'
  // Should be:
  //   opacity: 1,
  //   transform: '...'
  // Only fix if the line doesn't already end with a comma, semicolon, opening brace, or is part of a ternary
  const missingCommaRegex = /^(\s*\w[\w]*\s*:\s*(?:[^,\n{]|`[^`]*`|'[^']*'|"[^"]*"|\{[^}]*\}|\([^)]*\))*?)\s*\n(\s*\w[\w]*\s*:)/gm;
  let commaFixed = repaired;
  let commaMatch;
  // We need to do this iteratively because matches can overlap
  let iterations = 0;
  while ((commaMatch = missingCommaRegex.exec(commaFixed)) !== null && iterations < 50) {
    const fullMatch = commaMatch[0];
    const beforeNewline = commaMatch[1];
    const afterNewline = commaMatch[2];
    // Only fix if the line doesn't already end with a comma, semicolon, opening brace, or is part of a ternary
    if (!beforeNewline.trimEnd().endsWith(",") && !beforeNewline.trimEnd().endsWith(";") && !beforeNewline.trimEnd().endsWith("{") && !beforeNewline.trimEnd().endsWith("(")) {
      const fixed = beforeNewline + ",\n" + afterNewline;
      commaFixed = commaFixed.replace(fullMatch, fixed);
      repairs.push(`Added missing comma before '${afterNewline.trim()}'`);
    }
    iterations++;
    missingCommaRegex.lastIndex = 0; // Reset for iterative fixing
  }
  repaired = commaFixed;

  // ── Repair 2: Fix extra closing parentheses in map/filter patterns ────
  // Pattern: )))} should be ))}
  repaired = repaired.replace(/\)\)\)\}/g, (match, offset) => {
    // Check if this is inside a .map().map() double nesting — if so, leave it
    const contextBefore = repaired.slice(Math.max(0, offset - 200), offset);
    const mapCount = (contextBefore.match(/\.map\s*\(/g) || []).length;
    const closedMaps = (contextBefore.match(/\)\)\}/g) || []).length;
    if (mapCount - closedMaps >= 2) {
      return match; // Double nesting, leave as-is
    }
    repairs.push("Fixed extra closing parenthesis in map/filter pattern: ')))}' → '))}'");
    return "))}";
  });

  // ── Repair 3: Fix unbalanced braces by closing them ───────────────────
  const balance = checkBracketBalance(repaired);
  if (balance.braceCount > 0) {
    // Add missing closing braces
    for (let i = 0; i < balance.braceCount; i++) {
      repaired = repaired.trimEnd() + "\n}";
    }
    repairs.push(`Added ${balance.braceCount} missing closing brace(s)`);
  }
  if (balance.parenCount > 0) {
    // Add missing closing parentheses
    for (let i = 0; i < balance.parenCount; i++) {
      repaired = repaired.trimEnd() + "\n)";
    }
    repairs.push(`Added ${balance.parenCount} missing closing parenthesis(es)`);
  }

  // ── Repair 4: Remove extra closing braces/parens at the end ───────────
  if (balance.braceCount < 0) {
    // Remove extra closing braces from the end
    let trimmed = repaired.trimEnd();
    let removed = 0;
    while (removed < Math.abs(balance.braceCount) && trimmed.endsWith("}")) {
      trimmed = trimmed.slice(0, -1).trimEnd();
      removed++;
    }
    if (removed > 0) {
      repaired = trimmed;
      repairs.push(`Removed ${removed} extra closing brace(s)`);
    }
  }
  if (balance.parenCount < 0) {
    let trimmed = repaired.trimEnd();
    let removed = 0;
    while (removed < Math.abs(balance.parenCount) && trimmed.endsWith(")")) {
      trimmed = trimmed.slice(0, -1).trimEnd();
      removed++;
    }
    if (removed > 0) {
      repaired = trimmed;
      repairs.push(`Removed ${removed} extra closing parenthesis(es)`);
    }
  }

  // ── Repair 5: Ensure component ends with semicolon ────────────────────
  const trimmedEnd = repaired.trimEnd();
  if (trimmedEnd.endsWith("}") && !trimmedEnd.endsWith("};")) {
    repaired = trimmedEnd + ";";
    repairs.push("Added missing semicolon at end of component");
  }

  return { code: repaired, repairs };
}

// ── Babel Parse Validation ──────────────────────────────────────────────────

/**
 * Attempts to parse the code with Babel to verify it is valid JSX/TSX.
 * Returns null if valid, or the error message if invalid.
 */
function tryBabelParse(code: string): string | null {
  try {
    transform(code, {
      transforms: ["jsx", "typescript"],
    });
    return null;
  } catch (err) {
    return (err as Error).message || "Unknown parse error";
  }
}

// ── Main Validation Pipeline ────────────────────────────────────────────────

/**
 * Full validation and repair pipeline for generated Remotion component code.
 *
 * 1. Check bracket balance
 * 2. Detect structural issues
 * 3. Attempt auto-repair
 * 4. Verify repaired code with Babel
 *
 * Returns a ValidationReport with the repaired code if successful.
 */
export function validateAndRepairCode(code: string): ValidationReport {
  const errors: ValidationError[] = [];

  // Step 1: Check bracket balance
  const balance = checkBracketBalance(code);
  errors.push(...balance.errors);

  // Step 2: Detect structural issues
  const structuralErrors = detectStructuralIssues(code);
  errors.push(...structuralErrors);

  // Step 3: Try Babel parse on the original code first
  // Wrap in a component declaration like the compiler does
  const wrappedOriginal = `const ValidationCheck = () => {\n${code}\n};`;
  const originalParseError = tryBabelParse(wrappedOriginal);

  if (!originalParseError) {
    // Code is valid as-is!
    return {
      isValid: true,
      errors: [],
      repairedCode: null,
      repairApplied: false,
    };
  }

  // Step 4: Attempt auto-repair
  const { code: repairedCode, repairs } = repairGeneratedCode(code);

  if (repairs.length === 0) {
    // No repairs were made, code is still invalid
    errors.push({
      type: "syntax_error",
      message: originalParseError,
    });
    return {
      isValid: false,
      errors,
      repairedCode: null,
      repairApplied: false,
    };
  }

  // Step 5: Verify repaired code with Babel
  const wrappedRepaired = `const ValidationCheck = () => {\n${repairedCode}\n};`;
  const repairedParseError = tryBabelParse(wrappedRepaired);

  if (!repairedParseError) {
    // Repair succeeded!
    console.log(`[JSX Validator] Auto-repair succeeded. Repairs applied: ${repairs.join(", ")}`);
    return {
      isValid: true,
      errors: [],
      repairedCode,
      repairApplied: true,
    };
  }

  // Repair did not fix the issue
  errors.push({
    type: "syntax_error",
    message: `After repair attempt: ${repairedParseError}`,
  });

  return {
    isValid: false,
    errors,
    repairedCode: null,
    repairApplied: false,
  };
}

/**
 * Quick check: is the code valid TSX?
 * Returns true/false without attempting repair.
 */
export function isValidTSX(code: string): boolean {
  const balance = checkBracketBalance(code);
  if (!balance.balanced) return false;

  const wrapped = `const Check = () => {\n${code}\n};`;
  return tryBabelParse(wrapped) === null;
}
