import { extractComponentCode, validateGptResponse } from '../src/helpers/sanitize-response';

const sampleCode = `/*
 * Generated by Volviq V10 Premium Motion Engine
 */

import React from 'react';
import { AbsoluteFill } from 'remotion';

const Scene1 = () => {
  return <AbsoluteFill style={{ background: 'red' }}>Scene 1</AbsoluteFill>;
};

export const VolviqAnimation = () => {
  return (
    <AbsoluteFill>
      <Scene1 />
    </AbsoluteFill>
  );
};`;

console.log('--- TEST 1: Standard composition ---');
const parsed1 = extractComponentCode(sampleCode);
console.log('Parsed code length:', parsed1.length);
console.log('Does it contain VolviqAnimation?', parsed1.includes('VolviqAnimation'));
console.log('Validation:', validateGptResponse(parsed1));

console.log('\n--- TEST 2: Unbalanced brace in comment ---');
const sampleCode2 = `/*
 * Generated by Volviq V10 { Premium Motion Engine
 */

import React from 'react';
import { AbsoluteFill } from 'remotion';

const Scene1 = () => {
  return <AbsoluteFill>Scene 1</AbsoluteFill>;
};

export const VolviqAnimation = () => {
  return (
    <AbsoluteFill>
      <Scene1 />
    </AbsoluteFill>
  );
};`;

const parsed2 = extractComponentCode(sampleCode2);
console.log('Parsed code length:', parsed2.length);
console.log('Does it contain VolviqAnimation?', parsed2.includes('VolviqAnimation'));
console.log('Validation:', validateGptResponse(parsed2));

console.log('\n--- TEST 3: Arrow function in helpers ---');
const sampleCode3 = `import React from 'react';
const getDelay = (x) => x * 5;

const Scene1 = () => {
  return <AbsoluteFill>Scene 1</AbsoluteFill>;
};

export const VolviqAnimation = () => {
  return <AbsoluteFill><Scene1 /></AbsoluteFill>;
};`;

const parsed3 = extractComponentCode(sampleCode3);
console.log('Parsed code length:', parsed3.length);
console.log('Does it contain VolviqAnimation?', parsed3.includes('VolviqAnimation'));
console.log('Validation:', validateGptResponse(parsed3));
